name: pymer
# forge is needed for some of the packages
channels:
- default
- conda-forge

dependencies:
- python>=3.8
- pip
- numpy
- six
- matplotlib
- h5py
- scipy
- pandas
- pyexcel
- pyexcel-ods3
- pyexcel-xlsx
- libiconv # Required for pyexcel to work properly under python3.8
- scikit-learn
- pip:
  - pyglmnet
  - pycorrelate
