name: pymer
# forge is needed for some of the packages
channels:
- default
- conda-forge

dependencies:
- python>=3.6
- pip
- numpy
- matplotlib
- h5py
- scipy
- pandas
- pyexcel
- pyexcel-ods3
- pyexcel-xlsx
- pip:
  - pyglmnet
  - pycorrelate
